version: 0.2

env:
  variables:
    TD_BUILD_VERSION: "6.10.0"
    TD_BUILD_ITERATION: "1"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  build:
    commands:
      - docker build . --no-cache
      # - command
    finally:
      - docker tag td-agent:$TD_BUILD_VERSION-$TD_BUILD_ITERATION
      # - command
  post_build:
    commands:
      # - command
    #finally:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
    # - name
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - path
    # - path
