version: 0.2

env:
  variables:
    LANG: "C.UTF-8"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region eu-west-1)
  build:
    commands:
      - env
      - docker build . -f Dockerfile.base --no-cache -t td-agent
      - docker tag td-agent:latest 728193454066.dkr.ecr.eu-west-1.amazonaws.com/td-agent:latest
      # - command
    finally:
      # - command
  post_build:
    commands:
      - docker push 728193454066.dkr.ecr.eu-west-1.amazonaws.com/td-agent:latest
      # - command
    #finally:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
    # - name
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - path
    # - path
