version: 0.2

env:
  variables:
    LANG: "C.UTF-8"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  pre_build:
    commands:
      # Install an environment suitable for running rake
      - /usr/bin/apt-get update
      - /usr/bin/apt-get install software-properties-common -y
      - apt-add-repository ppa:brightbox/ruby-ng -y
      - apt-get update
      - apt-get install ruby2.3 --yes
      - apt-get install ruby2.3-dev --yes
      - apt-get install ruby-switch --yes
      - /usr/bin/ruby-switch --set ruby2.3
      - /usr/bin/gem install bundler --no-rdoc --no-ri
      - bundle install --with=test --without=default
      # Get a login
      - $(aws ecr get-login --no-include-email --region eu-west-1)
  build:
    commands:
      - rake hive:buildall
      # - command
    finally:
      # - command
  post_build:
    commands:
      # - command
    #finally:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
    # - name
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - path
    # - path
