dir 'plugin_gems'
download "httpclient", "2.7.1"
download "uuidtools", "2.1.5"
download "string-scrub", "0.0.5"
download "fluent-plugin-rewrite-tag-filter", "1.5.4"
download "statsd-ruby", "1.3.0"
download "fluent-plugin-statsd", "1.0.3"
download "fluent-plugin-secure-forward", "0.4.3"
download "fluent-plugin-elasticsearch", "1.9.5"
download "fluent-plugin-aws-elasticsearch-service", "0.1.6"
download "fluent-plugin-cloudwatch-ingest", "1.5.0"
